name: Compile LaTeX to PDF

on:
  push:
    paths:
      - 'Hardware Software Co Design/**/*.tex'
      - 'Real Time Systems/**/*.tex'

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # Retain credentials for git push

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-publishers texlive-science latexmk

      - name: Compile LaTeX files in "Hardware Software Co Design"
        run: |
          mkdir -p "Hardware Software Co Design/Compiled PDF"
          cd "Hardware Software Co Design"
          shopt -s nullglob
          for tex_file in *.tex; do
            latexmk -pdf -interaction=nonstopmode "$tex_file"
            mv "${tex_file%.tex}.pdf" "Compiled PDF/"
            latexmk -c
          done
          shopt -u nullglob

      - name: Compile LaTeX files in "Real Time Systems"
        run: |
          mkdir -p "Real Time Systems/Compiled PDF"
          cd "Real Time Systems"
          shopt -s nullglob
          for tex_file in *.tex; do
            latexmk -pdf -interaction=nonstopmode "$tex_file"
            mv "${tex_file%.tex}.pdf" "Compiled PDF/"
            latexmk -c
          done
          shopt -u nullglob

      - name: Commit and push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          git commit -m "Auto-compiled PDFs" || echo "No changes to commit"
          git push
